"""Shared loading helpers for the free-startup-credits build and validation scripts.

Single place that knows where things live and how they are parsed, so build.py
and validate.py can never disagree about the data.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

DATA = ROOT / "data"
PROGRAMS_DIR = DATA / "programs"
CATEGORIES_FILE = DATA / "categories.yml"
REGIONS_FILE = DATA / "regions.yml"
COLLECTIONS_FILE = DATA / "collections.yml"

SCHEMA_DIR = ROOT / "schema"
SCHEMA_BASE = SCHEMA_DIR / "program.schema.base.json"
SCHEMA_OUT = SCHEMA_DIR / "program.schema.json"

TEMPLATES_DIR = ROOT / "templates"
CATEGORIES_OUT = ROOT / "categories"
COLLECTIONS_OUT = ROOT / "collections"
PROGRAMS_OUT = ROOT / "programs"
API_OUT = ROOT / "api"
README_OUT = ROOT / "README.md"

# The public commitment. Entries older than this are surfaced for re-verification.
REVERIFY_DAYS = 180
STALE_INFO_DAYS = 120

GENERATED_BANNER = (
    "<!-- AUTOGENERATED FROM data/ -- DO NOT EDIT THIS FILE. Run `make build`. -->"
)


def load_yaml(path: Path):
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def load_categories() -> list[dict]:
    return load_yaml(CATEGORIES_FILE)["categories"]


def load_regions() -> dict:
    return load_yaml(REGIONS_FILE)


def load_collections() -> dict:
    return load_yaml(COLLECTIONS_FILE)


def category_ids() -> list[str]:
    return [c["id"] for c in load_categories()]


def region_group_ids() -> list[str]:
    return list(load_regions()["groups"].keys())


def load_programs() -> list[dict]:
    """Every program file, sorted by slug. The filename is the authoritative slug."""
    programs = []
    if not PROGRAMS_DIR.is_dir():
        return programs
    for path in sorted(PROGRAMS_DIR.glob("*.yml")):
        doc = load_yaml(path)
        if doc is None:
            continue
        doc["_file"] = path.relative_to(ROOT).as_posix()
        doc["_filename_slug"] = path.stem
        programs.append(doc)
    return programs


def build_schema() -> dict:
    """Inject the generated enums into the authored base schema.

    Keeping categories and region groups in one source of truth is what stops the
    schema enum, the issue-form dropdown and the README from drifting apart.
    """
    schema = json.loads(SCHEMA_BASE.read_text(encoding="utf-8"))

    schema["properties"]["category"]["enum"] = category_ids()

    groups = "|".join(sorted(region_group_ids()))
    region_pattern = f"^([A-Z]{{2}}|{groups})$"
    for field in ("regions", "excluded_regions"):
        schema["properties"][field]["items"]["pattern"] = region_pattern

    return schema


def write_if_changed(path: Path, content: str) -> bool:
    """Write only on a real change, so `git diff --exit-code` stays meaningful."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True
